# Generated by Django 4.0.6 on 2023-05-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='facebook_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='github_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='twitter_url',
            field=models.URLField(default=''),
        ),
    ]
