# Generated by Django 4.0.6 on 2023-05-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_facebook_url_employee_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='facebook_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='github_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='twitter_url',
            field=models.URLField(default=''),
        ),
    ]
