# Generated by Django 4.0.6 on 2023-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='google_map_url',
            field=models.URLField(default='', max_length=3000),
        ),
    ]
