# Generated by Django 4.0.6 on 2023-05-30 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('comment', models.CharField(default='', max_length=99999)),
                ('price_min', models.IntegerField(default=10)),
                ('price_max', models.IntegerField(default=10)),
                ('applicating_until', models.DateField()),
                ('pj_start_date', models.DateField()),
                ('pj_end_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'applicating'), (1, 'completed'), (2, 'canceled')], default=0)),
                ('thumbnail1', models.CharField(default='thumbnail1.png', max_length=30)),
                ('thumbnail2', models.CharField(default='thumbnail2.png', max_length=30)),
                ('thumbnail3', models.CharField(default='thumbnail3.png', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdmin.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdmin.prefecture')),
                ('work_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdmin.workhour')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdmin.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAdmin.skill')),
            ],
        ),
        migrations.CreateModel(
            name='JobEmployeeMessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
