# Generated by Django 4.0.6 on 2023-06-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='thumbnail1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='thumbnail2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='thumbnail3',
        ),
    ]
